# Sourced from https://github.com/denis-ismailaj/d2-diagrams-icons (v0.1.0)
programming: {
  framework: {
    Fastify: {
      icon: https://raw.githubusercontent.com/fastify/graphics/96648545/fastify-1000px-square-02.svg
      shape: image
    }
    JetpackCompose: {
      icon: https://raw.githubusercontent.com/JetBrains/compose-multiplatform/e5d12d04/artwork/compose-logo.svg
      shape: image
    }
  }
}
firebase: {
  grow: {
    Analytics: {
      icon: https://www.gstatic.com/analytics-suite/header/suite/v2/ic_analytics.svg
      shape: image
    }
  }
}
saas: {
  identity: {
    Google: {
      icon: https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg
      shape: image
    }
    Apple: {
      icon: https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/391px-Apple_logo_black.svg.png
      shape: image
    }
  }
  payments: {
    PayPal: {
      icon: https://upload.wikimedia.org/wikipedia/commons/3/31/PayPal_Logo2014.svg
      shape: image
    }
  }
}
